### YamlMime:ManagedReference
items:
- uid: MLEM.Formatting.FormatSettings
  commentId: T:MLEM.Formatting.FormatSettings
  id: FormatSettings
  parent: MLEM.Formatting
  children:
  - MLEM.Formatting.FormatSettings.Default
  - MLEM.Formatting.FormatSettings.DropShadowColor
  - MLEM.Formatting.FormatSettings.DropShadowOffset
  - MLEM.Formatting.FormatSettings.TypingSpeed
  - MLEM.Formatting.FormatSettings.WobbleHeightModifier
  - MLEM.Formatting.FormatSettings.WobbleModifier
  langs:
  - csharp
  - vb
  name: FormatSettings
  nameWithType: FormatSettings
  fullName: MLEM.Formatting.FormatSettings
  type: Class
  source:
    remote:
      path: MLEM/Formatting/Obsolete/FormatSettings.cs
      branch: master
      repo: https://github.com/Ellpeck/MLEM
    id: FormatSettings
    path: ../MLEM/Formatting/Obsolete/FormatSettings.cs
    startLine: 5
  assemblies:
  - MLEM
  namespace: MLEM.Formatting
  syntax:
    content: >-
      [Obsolete("Use the new text formatting system in MLEM.Formatting instead")]

      public class FormatSettings : GenericDataHolder
    content.vb: >-
      <Obsolete("Use the new text formatting system in MLEM.Formatting instead")>

      Public Class FormatSettings

          Inherits GenericDataHolder
  inheritance:
  - System.Object
  - MLEM.Misc.GenericDataHolder
  inheritedMembers:
  - MLEM.Misc.GenericDataHolder.SetData(System.String,System.Object)
  - MLEM.Misc.GenericDataHolder.GetData``1(System.String)
  - MLEM.Misc.GenericDataHolder.GetDataKeys
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.ObsoleteAttribute
    ctor: System.ObsoleteAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Use the new text formatting system in MLEM.Formatting instead
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: MLEM.Formatting.FormatSettings.Default
  commentId: F:MLEM.Formatting.FormatSettings.Default
  id: Default
  parent: MLEM.Formatting.FormatSettings
  langs:
  - csharp
  - vb
  name: Default
  nameWithType: FormatSettings.Default
  fullName: MLEM.Formatting.FormatSettings.Default
  type: Field
  source:
    remote:
      path: MLEM/Formatting/Obsolete/FormatSettings.cs
      branch: master
      repo: https://github.com/Ellpeck/MLEM
    id: Default
    path: ../MLEM/Formatting/Obsolete/FormatSettings.cs
    startLine: 8
  assemblies:
  - MLEM
  namespace: MLEM.Formatting
  syntax:
    content: public static readonly FormatSettings Default
    return:
      type: MLEM.Formatting.FormatSettings
    content.vb: Public Shared ReadOnly Default As FormatSettings
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: MLEM.Formatting.FormatSettings.WobbleModifier
  commentId: F:MLEM.Formatting.FormatSettings.WobbleModifier
  id: WobbleModifier
  parent: MLEM.Formatting.FormatSettings
  langs:
  - csharp
  - vb
  name: WobbleModifier
  nameWithType: FormatSettings.WobbleModifier
  fullName: MLEM.Formatting.FormatSettings.WobbleModifier
  type: Field
  source:
    remote:
      path: MLEM/Formatting/Obsolete/FormatSettings.cs
      branch: master
      repo: https://github.com/Ellpeck/MLEM
    id: WobbleModifier
    path: ../MLEM/Formatting/Obsolete/FormatSettings.cs
    startLine: 10
  assemblies:
  - MLEM
  namespace: MLEM.Formatting
  syntax:
    content: public float WobbleModifier
    return:
      type: System.Single
    content.vb: Public WobbleModifier As Single
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: MLEM.Formatting.FormatSettings.WobbleHeightModifier
  commentId: F:MLEM.Formatting.FormatSettings.WobbleHeightModifier
  id: WobbleHeightModifier
  parent: MLEM.Formatting.FormatSettings
  langs:
  - csharp
  - vb
  name: WobbleHeightModifier
  nameWithType: FormatSettings.WobbleHeightModifier
  fullName: MLEM.Formatting.FormatSettings.WobbleHeightModifier
  type: Field
  source:
    remote:
      path: MLEM/Formatting/Obsolete/FormatSettings.cs
      branch: master
      repo: https://github.com/Ellpeck/MLEM
    id: WobbleHeightModifier
    path: ../MLEM/Formatting/Obsolete/FormatSettings.cs
    startLine: 11
  assemblies:
  - MLEM
  namespace: MLEM.Formatting
  syntax:
    content: public float WobbleHeightModifier
    return:
      type: System.Single
    content.vb: Public WobbleHeightModifier As Single
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: MLEM.Formatting.FormatSettings.TypingSpeed
  commentId: F:MLEM.Formatting.FormatSettings.TypingSpeed
  id: TypingSpeed
  parent: MLEM.Formatting.FormatSettings
  langs:
  - csharp
  - vb
  name: TypingSpeed
  nameWithType: FormatSettings.TypingSpeed
  fullName: MLEM.Formatting.FormatSettings.TypingSpeed
  type: Field
  source:
    remote:
      path: MLEM/Formatting/Obsolete/FormatSettings.cs
      branch: master
      repo: https://github.com/Ellpeck/MLEM
    id: TypingSpeed
    path: ../MLEM/Formatting/Obsolete/FormatSettings.cs
    startLine: 12
  assemblies:
  - MLEM
  namespace: MLEM.Formatting
  syntax:
    content: public float TypingSpeed
    return:
      type: System.Single
    content.vb: Public TypingSpeed As Single
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: MLEM.Formatting.FormatSettings.DropShadowColor
  commentId: F:MLEM.Formatting.FormatSettings.DropShadowColor
  id: DropShadowColor
  parent: MLEM.Formatting.FormatSettings
  langs:
  - csharp
  - vb
  name: DropShadowColor
  nameWithType: FormatSettings.DropShadowColor
  fullName: MLEM.Formatting.FormatSettings.DropShadowColor
  type: Field
  source:
    remote:
      path: MLEM/Formatting/Obsolete/FormatSettings.cs
      branch: master
      repo: https://github.com/Ellpeck/MLEM
    id: DropShadowColor
    path: ../MLEM/Formatting/Obsolete/FormatSettings.cs
    startLine: 13
  assemblies:
  - MLEM
  namespace: MLEM.Formatting
  syntax:
    content: public Color DropShadowColor
    return:
      type: Microsoft.Xna.Framework.Color
    content.vb: Public DropShadowColor As Color
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: MLEM.Formatting.FormatSettings.DropShadowOffset
  commentId: F:MLEM.Formatting.FormatSettings.DropShadowOffset
  id: DropShadowOffset
  parent: MLEM.Formatting.FormatSettings
  langs:
  - csharp
  - vb
  name: DropShadowOffset
  nameWithType: FormatSettings.DropShadowOffset
  fullName: MLEM.Formatting.FormatSettings.DropShadowOffset
  type: Field
  source:
    remote:
      path: MLEM/Formatting/Obsolete/FormatSettings.cs
      branch: master
      repo: https://github.com/Ellpeck/MLEM
    id: DropShadowOffset
    path: ../MLEM/Formatting/Obsolete/FormatSettings.cs
    startLine: 14
  assemblies:
  - MLEM
  namespace: MLEM.Formatting
  syntax:
    content: public Vector2 DropShadowOffset
    return:
      type: Microsoft.Xna.Framework.Vector2
    content.vb: Public DropShadowOffset As Vector2
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: MLEM.Formatting
  commentId: N:MLEM.Formatting
  name: MLEM.Formatting
  nameWithType: MLEM.Formatting
  fullName: MLEM.Formatting
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: MLEM.Misc.GenericDataHolder
  commentId: T:MLEM.Misc.GenericDataHolder
  parent: MLEM.Misc
  name: GenericDataHolder
  nameWithType: GenericDataHolder
  fullName: MLEM.Misc.GenericDataHolder
- uid: MLEM.Misc.GenericDataHolder.SetData(System.String,System.Object)
  commentId: M:MLEM.Misc.GenericDataHolder.SetData(System.String,System.Object)
  parent: MLEM.Misc.GenericDataHolder
  isExternal: true
  name: SetData(String, Object)
  nameWithType: GenericDataHolder.SetData(String, Object)
  fullName: MLEM.Misc.GenericDataHolder.SetData(System.String, System.Object)
  spec.csharp:
  - uid: MLEM.Misc.GenericDataHolder.SetData(System.String,System.Object)
    name: SetData
    nameWithType: GenericDataHolder.SetData
    fullName: MLEM.Misc.GenericDataHolder.SetData
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: MLEM.Misc.GenericDataHolder.SetData(System.String,System.Object)
    name: SetData
    nameWithType: GenericDataHolder.SetData
    fullName: MLEM.Misc.GenericDataHolder.SetData
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: MLEM.Misc.GenericDataHolder.GetData``1(System.String)
  commentId: M:MLEM.Misc.GenericDataHolder.GetData``1(System.String)
  parent: MLEM.Misc.GenericDataHolder
  isExternal: true
  name: GetData<T>(String)
  nameWithType: GenericDataHolder.GetData<T>(String)
  fullName: MLEM.Misc.GenericDataHolder.GetData<T>(System.String)
  nameWithType.vb: GenericDataHolder.GetData(Of T)(String)
  fullName.vb: MLEM.Misc.GenericDataHolder.GetData(Of T)(System.String)
  name.vb: GetData(Of T)(String)
  spec.csharp:
  - uid: MLEM.Misc.GenericDataHolder.GetData``1(System.String)
    name: GetData<T>
    nameWithType: GenericDataHolder.GetData<T>
    fullName: MLEM.Misc.GenericDataHolder.GetData<T>
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: MLEM.Misc.GenericDataHolder.GetData``1(System.String)
    name: GetData(Of T)
    nameWithType: GenericDataHolder.GetData(Of T)
    fullName: MLEM.Misc.GenericDataHolder.GetData(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: MLEM.Misc.GenericDataHolder.GetDataKeys
  commentId: M:MLEM.Misc.GenericDataHolder.GetDataKeys
  parent: MLEM.Misc.GenericDataHolder
  name: GetDataKeys()
  nameWithType: GenericDataHolder.GetDataKeys()
  fullName: MLEM.Misc.GenericDataHolder.GetDataKeys()
  spec.csharp:
  - uid: MLEM.Misc.GenericDataHolder.GetDataKeys
    name: GetDataKeys
    nameWithType: GenericDataHolder.GetDataKeys
    fullName: MLEM.Misc.GenericDataHolder.GetDataKeys
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: MLEM.Misc.GenericDataHolder.GetDataKeys
    name: GetDataKeys
    nameWithType: GenericDataHolder.GetDataKeys
    fullName: MLEM.Misc.GenericDataHolder.GetDataKeys
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: MLEM.Misc
  commentId: N:MLEM.Misc
  name: MLEM.Misc
  nameWithType: MLEM.Misc
  fullName: MLEM.Misc
- uid: MLEM.Formatting.FormatSettings
  commentId: T:MLEM.Formatting.FormatSettings
  parent: MLEM.Formatting
  name: FormatSettings
  nameWithType: FormatSettings
  fullName: MLEM.Formatting.FormatSettings
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  name: Single
  nameWithType: Single
  fullName: System.Single
- uid: Microsoft.Xna.Framework.Color
  commentId: T:Microsoft.Xna.Framework.Color
  parent: Microsoft.Xna.Framework
  isExternal: true
  name: Color
  nameWithType: Color
  fullName: Microsoft.Xna.Framework.Color
- uid: Microsoft.Xna.Framework
  commentId: N:Microsoft.Xna.Framework
  isExternal: true
  name: Microsoft.Xna.Framework
  nameWithType: Microsoft.Xna.Framework
  fullName: Microsoft.Xna.Framework
- uid: Microsoft.Xna.Framework.Vector2
  commentId: T:Microsoft.Xna.Framework.Vector2
  parent: Microsoft.Xna.Framework
  isExternal: true
  name: Vector2
  nameWithType: Vector2
  fullName: Microsoft.Xna.Framework.Vector2
